config/routes.rb
Rails.application.routes.draw do
  root "cities#index"
  devise_for :users
  resources :cities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name, :country, :highlights , :image)
    end
end

app/controllers/turbo_devise_controller.rb
#this code is from Github Issues solving the Bug of NoMethodError in Devise::RegistrationsController#create undefined method `user_url' for #<Devise::RegistrationsController:0x0000000000e088>
# responds with html & turbo instat of just html 


class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => e 
            if get?
                raise e
            elsif has_errors? && default_action   
                render rendering_options.merge(formats: :html, status: :unprocessable_entity)
            else
                redirect_to navigation_location
            end
        end
    end 

    self.responder = Responder 
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cities/_city.html.erb
<div class="row row-cols-1 row-cols-md-2 g-4">
<div class="col">
<div class="card" style="width: 18rem;">

<%= image_tag city.image if city.image.attached? %>


<div id="<%= dom_id city %>">
<div class="card-body">
<p>
    <strong>Name:</strong>
    <%= city.name %>
  </p>
  
  
  <p>
    <strong>Country:</strong>
    <%= city.country %>
  </p>

  <p>
    <strong>Highlights:</strong>
    <%= city.highlights %>
  </p>

</div>
</div>
</div>
</div>
</div>
</div>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>   
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :highlights, style: "display: block" %>
    <%= form.text_area :highlights %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cities</h1>

<div id="cities">
<% @cities.each do |city| %>
<div>
<%= render city %>
    <p>
      <%= link_to "Show this city", city %>
    </p>

  <% end %>
</div>
</div>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>
<div>

<%= render @city %>
<br/>

    <%= link_to "Edit this city", edit_city_path(@city) %> |
    <%= link_to "Back to cities", cities_path %>
    <%= button_to "Destroy this city", @city, method: :delete %>

 </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">


  <div class="container-fluid">
    <%= link_to "Bon Voyage" , root_path, class:'navbar-brand'%>
    
    <%= link_to "Add New City" , new_city_path, class:'navbar-brand'%>
    <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-brand'%>
    <%= link_to "Login" , user_session_path, class: 'navbar-brand'%>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'navbar-brand'%>

  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voyager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    



    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
  <%= render'layouts/navbar' %>
  
  </header>

  <main>
    <div class="container">
  
    <%= yield %>
   
    </div>
  </main>
    
  </body>
</html>